# API access credentials
username: user  # Username for API authentication
password: password # Password for API authentication

# URLs da API
loginUrl: http://ffplayout:8787/auth/login/  # URL to log in to the API
programUrl: http://ffplayout:8787/api/playlist/1  # URL to search for the program playlist

# Time and file settings
currentTime: 08:00:00  # Start time for calculating program times
outputFile: /home/user/Documents/program.json  # Path where the JSON file will be saved

# Renaming programs
rename:
  Breaks: Intervalo comercial  #  Renames the program "Breaks" to "Commercial Break"
  vivo-SucessoNoCampo: Sucesso No Campo | AO VIVO  # Renames the program "vivo-SucessoNoCampo" to "Sucesso No Campo | LIVE"

# Programs to ignore
ignore:
  - Vinhetas  # Ignore the "Vinhetas" program (it will not be included in the JSON, but the time will be added)

# Program synopsis
synopsis:
  Sucesso No Campo: "Gerando 42 horas de conteúdo mensal entre Programas AO VIVO e gravado. Temos ainda boletins diários, cotações, mercado, clima, tecnologia, análise de especialistas, reportagens especiais, coberturas de dias de campo, lançamentos de produtos, feiras e eventos; tudo para contribuir com as tomadas de decisões do nosso telespectador (o produtor rural)."
  vivo-SucessoNoCampo: "Programa ao vivo com as últimas notícias e análises do agronegócio."
