# Credenciais de acesso à API
username: admin  # Nome de usuário para autenticação na API
password: admin  # Senha para autenticação na API

# URLs da API
loginUrl: http://ffplayout:8787/auth/login/  # URL para fazer login na API
programUrl: http://fplayout:8787/api/playlist/1  # URL para buscar a playlist de programas

# Configurações de tempo e arquivo
currentTime: 08:00:00  # Hora inicial para o cálculo dos horários dos programas
outputFile: /home/user/Documents/program.json  # Caminho onde o arquivo JSON será salvo

# Renomeação de programas
rename:
  Breaks: Intervalo comercial  # Renomeia o programa "Breaks" para "Intervalo comercial"
  vivo-SucessoNoCampo: Sucesso No Campo | AO VIVO  # Renomeia o programa "vivo-SucessoNoCampo" para "Sucesso No Campo | AO VIVO"

# Programas a serem ignorados
ignore:
  - Vinhetas  # Ignora o programa "Vinhetas" (não será incluído no JSON, mas o tempo será somado)

# Sinopses dos programas
sinopses:
  Sucesso No Campo: "Gerando 42 horas de conteúdo mensal entre Programas AO VIVO e gravado. Temos ainda boletins diários, cotações, mercado, clima, tecnologia, análise de especialistas, reportagens especiais, coberturas de dias de campo, lançamentos de produtos, feiras e eventos; tudo para contribuir com as tomadas de decisões do nosso telespectador (o produtor rural)."
  vivo-SucessoNoCampo: "Programa ao vivo com as últimas notícias e análises do agronegócio."